apiVersion: v1
kind: Service
metadata:
  name: weather-app-database
spec:
  type: ClusterIP
  selector:
    component: weather-app-database
  ports:
    - port: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-database
spec:
  replicas: 1
  selector:
    matchLabels:
      component: weather-app-database
  template:
    metadata:
      labels:
        component: weather-app-database
    spec:
      containers:
        - name: postgres
          image: postgres:11.5
          env:
            - name: POSTGRES_DB
              value: weather_app
            - name: POSTGRES_USER
              value: postgresadmin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weather-app
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: dating-persistent-storage
              mountPath: /var/lib/postgres
      volumes:
        - name: dating-persistent-storage
          persistentVolumeClaim:
            claimName: weather-app-database-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-app-database-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
