apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: personal-website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      - name: personal-website
        image: blenz1/personal-website
        ports:
        - containerPort: 80