apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: brettlenz-com-tls
spec:
  secretName: brettlenz-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: brettlenz.com
  dnsNames:
    - brettlenz.com
    - www.brettlenz.com
    - dating-app.brettlenz.com
    - www.dating-app.brettlenz.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - brettlenz.com
          - www.brettlenz.com
          - dating-app.brettlenz.com
          - www.dating-app.brettlenz.com

