apiVersion: v1
kind: Service
metadata:
  name: dating-database
spec:
  type: ClusterIP
  selector:
    component: dating-database
  ports:
  - port: 3306


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: dating-database
spec:
  replicas: 1
  selector:
    matchLabels:
      component: dating-database
  template:
    metadata:
      labels:
        component: dating-database
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: dating-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: dating-persistent-storage
        persistentVolumeClaim:
          claimName: dating-database-claim


---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dating-database-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
